# Generated by Django 4.2.1 on 2023-07-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentRecord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentRecord.registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentRecord.student')),
            ],
        ),
        migrations.CreateModel(
            name='feeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentRecord.registration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentRecord.student')),
            ],
        ),
    ]
